// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/node.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitMessage struct {
	Height               int32       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Nodes                []*NodeHost `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InitMessage) Reset()         { *m = InitMessage{} }
func (m *InitMessage) String() string { return proto.CompactTextString(m) }
func (*InitMessage) ProtoMessage()    {}
func (*InitMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a57c11bd76aa, []int{0}
}

func (m *InitMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMessage.Unmarshal(m, b)
}
func (m *InitMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMessage.Marshal(b, m, deterministic)
}
func (m *InitMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMessage.Merge(m, src)
}
func (m *InitMessage) XXX_Size() int {
	return xxx_messageInfo_InitMessage.Size(m)
}
func (m *InitMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InitMessage proto.InternalMessageInfo

func (m *InitMessage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *InitMessage) GetNodes() []*NodeHost {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeHost struct {
	ConnString           string   `protobuf:"bytes,1,opt,name=connString,proto3" json:"connString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeHost) Reset()         { *m = NodeHost{} }
func (m *NodeHost) String() string { return proto.CompactTextString(m) }
func (*NodeHost) ProtoMessage()    {}
func (*NodeHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a57c11bd76aa, []int{1}
}

func (m *NodeHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHost.Unmarshal(m, b)
}
func (m *NodeHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHost.Marshal(b, m, deterministic)
}
func (m *NodeHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHost.Merge(m, src)
}
func (m *NodeHost) XXX_Size() int {
	return xxx_messageInfo_NodeHost.Size(m)
}
func (m *NodeHost) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHost.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHost proto.InternalMessageInfo

func (m *NodeHost) GetConnString() string {
	if m != nil {
		return m.ConnString
	}
	return ""
}

func init() {
	proto.RegisterType((*InitMessage)(nil), "InitMessage")
	proto.RegisterType((*NodeHost)(nil), "NodeHost")
}

func init() {
	proto.RegisterFile("proto/node.proto", fileDescriptor_c949a57c11bd76aa)
}

var fileDescriptor_c949a57c11bd76aa = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4f, 0xc3, 0x40,
	0x0c, 0x85, 0x5b, 0xa0, 0x11, 0x75, 0x3a, 0xd0, 0x1b, 0xa0, 0xca, 0x00, 0x55, 0xa6, 0xaa, 0xc3,
	0x55, 0x2a, 0x12, 0x3b, 0x48, 0xa0, 0x32, 0xc0, 0x90, 0x32, 0xb1, 0x5d, 0x13, 0x2b, 0x39, 0x51,
	0xec, 0x70, 0xb6, 0x90, 0xe0, 0xd7, 0xa3, 0x24, 0x45, 0x84, 0xed, 0xbe, 0xef, 0x2c, 0xfb, 0x3d,
	0x38, 0xab, 0x03, 0x2b, 0xaf, 0x88, 0x0b, 0xb4, 0xed, 0x33, 0x31, 0x9d, 0x91, 0xca, 0x05, 0x2c,
	0x0e, 0xee, 0xa2, 0x73, 0x1a, 0x1c, 0x89, 0xcb, 0xd5, 0x33, 0x75, 0x1f, 0xe9, 0x03, 0xc4, 0x8f,
	0xe4, 0xf5, 0x09, 0x45, 0x5c, 0x89, 0xe6, 0x1c, 0xa2, 0x0a, 0x7d, 0x59, 0xe9, 0x6c, 0x38, 0x1f,
	0x2e, 0x46, 0xd9, 0x81, 0xcc, 0x15, 0x8c, 0x9a, 0x0b, 0x32, 0x3b, 0x9a, 0x1f, 0x2f, 0xe2, 0xf5,
	0xd8, 0x3e, 0x73, 0x81, 0x1b, 0x16, 0xcd, 0x3a, 0x9f, 0x2e, 0xe1, 0xf4, 0x57, 0x99, 0x4b, 0x80,
	0x9c, 0x89, 0xb6, 0x1a, 0x3c, 0x95, 0xed, 0xa2, 0x71, 0xd6, 0x33, 0xeb, 0x0f, 0x88, 0x9b, 0xd9,
	0x2d, 0x86, 0x4f, 0x9f, 0xa3, 0x59, 0x02, 0x34, 0x11, 0xbc, 0xdb, 0xfb, 0x6f, 0x34, 0x13, 0xdb,
	0xcb, 0x93, 0xfc, 0xa3, 0x74, 0x60, 0x6e, 0x60, 0xba, 0x71, 0x54, 0xec, 0xf1, 0xe5, 0xaf, 0x89,
	0x99, 0xd8, 0x1e, 0x25, 0x53, 0x7b, 0xff, 0x5e, 0xeb, 0xd7, 0x6d, 0xfe, 0x96, 0xa1, 0xd4, 0x4c,
	0x82, 0xe9, 0xe0, 0x2e, 0x7a, 0x3d, 0xb1, 0xab, 0x7a, 0xb7, 0x8b, 0xda, 0xd6, 0xd7, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0x8b, 0xa0, 0x4c, 0x36, 0x01, 0x00, 0x00,
}
