// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transaction.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Inputs               []*TransactionInput  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TransactionOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Transaction) GetInputs() []*TransactionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type TransactionInput struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInput) Reset()         { *m = TransactionInput{} }
func (m *TransactionInput) String() string { return proto.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()    {}
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{1}
}

func (m *TransactionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInput.Unmarshal(m, b)
}
func (m *TransactionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInput.Marshal(b, m, deterministic)
}
func (m *TransactionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInput.Merge(m, src)
}
func (m *TransactionInput) XXX_Size() int {
	return xxx_messageInfo_TransactionInput.Size(m)
}
func (m *TransactionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInput proto.InternalMessageInfo

func (m *TransactionInput) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *TransactionInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionInput) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TransactionOutput struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionOutput) Reset()         { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string { return proto.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()    {}
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e80868f3cd63d0, []int{2}
}

func (m *TransactionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionOutput.Unmarshal(m, b)
}
func (m *TransactionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionOutput.Marshal(b, m, deterministic)
}
func (m *TransactionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionOutput.Merge(m, src)
}
func (m *TransactionOutput) XXX_Size() int {
	return xxx_messageInfo_TransactionOutput.Size(m)
}
func (m *TransactionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionOutput proto.InternalMessageInfo

func (m *TransactionOutput) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *TransactionOutput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*TransactionInput)(nil), "TransactionInput")
	proto.RegisterType((*TransactionOutput)(nil), "TransactionOutput")
}

func init() {
	proto.RegisterFile("proto/transaction.proto", fileDescriptor_80e80868f3cd63d0)
}

var fileDescriptor_80e80868f3cd63d0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b,
	0x28, 0x35, 0x30, 0x72, 0x71, 0x87, 0x20, 0x44, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a,
	0x33, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x4d, 0x2e, 0xb6,
	0xcc, 0xbc, 0x82, 0xd2, 0x92, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x41, 0x3d, 0x24,
	0x7d, 0x9e, 0x20, 0x99, 0x20, 0xa8, 0x02, 0x21, 0x1d, 0x2e, 0xf6, 0xfc, 0xd2, 0x12, 0xb0, 0x5a,
	0x66, 0xb0, 0x5a, 0x21, 0x64, 0xb5, 0xfe, 0x60, 0xa9, 0x20, 0x98, 0x12, 0x90, 0x13, 0x04, 0xd0,
	0x8d, 0x02, 0xb9, 0x23, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x18, 0xec, 0x0e, 0x9e, 0x20, 0x18,
	0x57, 0x48, 0x8c, 0x8b, 0x2d, 0x31, 0x37, 0xbf, 0x34, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x39, 0x08, 0xca, 0x13, 0x92, 0xe1, 0xe2, 0x2c, 0x28, 0x4d, 0xca, 0xc9, 0x4c, 0xf6, 0x4e, 0xad,
	0x94, 0x60, 0x06, 0xeb, 0x41, 0x08, 0x80, 0x64, 0x8b, 0x33, 0xd3, 0xf3, 0x12, 0x4b, 0x4a, 0x8b,
	0x52, 0x25, 0x58, 0x20, 0xb2, 0x70, 0x01, 0x25, 0x57, 0x2e, 0x41, 0x0c, 0x07, 0x92, 0xee, 0x04,
	0x27, 0xb6, 0x28, 0x16, 0x3d, 0xfd, 0x82, 0xa4, 0x24, 0x36, 0x70, 0xd8, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x39, 0xa2, 0x0f, 0xce, 0x76, 0x01, 0x00, 0x00,
}
